# Generated by Django 5.2.7 on 2025-10-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='toys',
            field=models.ManyToManyField(blank=True, to='main_app.toy'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='main_app.cat'),
        ),
    ]
